spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    open-in-view: false


  jpa:
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
